app/common/models/Project.php
<?php
namespace common\models;

use common\models\ext\AR;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\Expression;
use yii\db\Schema;

/**
 * Project model
 *
 * @property integer $id
 * @property integer $owner_id
 * @property string $name
 * @property string $description
 * @property integer $status
 * @property string $updated_at
 * @property string $created_at
 */
class Project extends AR
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%tbl_project}}';
    }

    /**
     * @inheritdoc
     */
    public function attributeTypes()
    {
        return [
            'id' => Schema::TYPE_PK,
            'owner_id' => Schema::TYPE_INTEGER,
            'name' => Schema::TYPE_STRING,
            'description' => Schema::TYPE_TEXT,
            'status' => Schema::TYPE_SMALLINT,
            'updated_at' => Schema::TYPE_TIMESTAMP,
            'created_at' => Schema::TYPE_TIMESTAMP,
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => '#',
            'owner_id' => Yii::t('project', 'User'),
            'name' => Yii::t('project', 'Name'),
            'description' => Yii::t('project', 'Description'),
            'status' => Yii::t('project', 'Status'),
            'updated_at' => Yii::t('project', 'Updated at'),
            'created_at' => Yii::t('project', 'Created at'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'value' => new Expression('NOW()')
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description', 'status', 'updated_at', 'created_at'], 'safe'],
        ];
    }

    /**
     * @return User
     */
    public function getOwner()
    {
        return $this->hasOne('\common\models\User', ['id' => 'owner_id'])->one();
    }

    /**
     * @return Chat[]
     */
    public function getChats()
    {
        return $this->hasOne('\common\models\Chat', ['project_id' => 'id'])->all();
    }

    /**
     * @return ActiveQuery
     */
    public function getHasUser()
    {
        return $this->hasMany(ProjectHasUser::className(), ['project_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])->via('hasUser');
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert = true)
    {
        $this->status = Project::STATUS_ACTIVE;
        $this->owner_id = Yii::$app->getUser()->getId();

        return parent::beforeSave($insert);
    }
}

app/frontend/controllers/ProjectController.php
<?php
namespace frontend\controllers;

use common\models\Chat;
use common\models\ChatHasUser;
use common\models\Project;
use common\models\Repository;
use common\models\User;
use frontend\filters\AccessRule;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * Class ProjectController
 */
class ProjectController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'class' => AccessRule::className(),
                    ],
                ],
            ],
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'logout' => ['post'],
//                ],
//            ],
        ];
	}

	/**
	 * @return string
	 */
	public function actionIndex()
	{
        return $this->render('index');
	}

    /**
     * @param null $id
     * @return string|Response
     */
	public function actionCreate($id = null)
	{
        if(!$id || null === ($project = Project::findOne($id))) {
            $project = new Project();
        }

        if($project->load(Yii::$app->request->post())) {
            $project->status = Project::STATUS_ACTIVE;
            $project->owner_id = Yii::$app->getUser()->getId();

            if($project->save()) {
                return $this->redirect(Url::to('index'));
            }
        }

		return $this->render('edit', ['project' => $project]);
	}

    /**
     * @param $id
     * @return string|Response
     */
	public function actionUpdate($id)
	{
		return $this->actionCreate($id);
	}

	/**
	 * @param $id
	 * @return string
	 */
	public function actionView($id)
	{
        $project = Project::findById($id);

        return $this->render('view', ['model' => $project]);
	}

    /**
     * @param $id
     * @return string
     * @throws BadRequestHttpException
     */
    public function actionCreateChat($id)
    {
        if(!Yii::$app->getRequest()->isAjax) {
            throw new BadRequestHttpException("Not found!", 404);
        }

        $project = Project::findById($id);

        $chat = new Chat([
            'project_id' => $project->id,
            'owner_id' => Yii::$app->user->getId(),
            'name' => $project->name . ' - Chat',
        ]);

        $chat->setScenario('create-chat');

        if($chat->load(Yii::$app->request->get())) {
            Yii::$app->response->format = Response::FORMAT_JSON;

            $chat->status = User::STATUS_ACTIVE;
            $errors = ActiveForm::validate($chat, $chat->attributes());

            if(empty($errors) && $chat->save()) {
                $chatUser = new ChatHasUser();
                $chatUser->chat_id = $chat->id;
                $chatUser->user_id = $chat->owner_id;
                $chatUser->save();
            }

            return $errors;
        }

        return $this->renderPartial('/chat/edit', ['model' => $chat]);
    }


}

app/frontend/controllers/RepositoryController.php
<?php
namespace frontend\controllers;

use common\models\Repository;
use ext\Repository\Helper;
use ext\WebSocket\Client;
use frontend\filters\AccessRule;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;

/**
 * Class RepositoryController
 */
class RepositoryController extends Controller
{
    /**
     * @var bool
     */
    public $enableCsrfValidation = false;

    /**
     * @inheritdoc
     */
//    public function behaviors()
//    {
//        return [
//            'access' => [
//                'class' => AccessControl::className(),
//                'rules' => [
//                    [
//                        'class' => AccessRule::className(),
//                    ],
//                ],
//            ],
//        ];
//    }

    /**
     * @param integer
     * @return string
     */
    public function actionCreate($pid)
    {
        $project = new Repository();

        if (is_numeric($pid) && $project->load(Yii::$app->request->post())) {
            $project->status = Repository::STATUS_ACTIVE;
            $project->owner_id = Yii::$app->getUser()->getId();
            $project->project_id = $pid;

            if ($project->save()) {
                return $this->redirect(Url::to(['/project/view', 'id' => $pid]));
            }
        }

        return $this->render('edit', ['project' => $project]);
    }

    /**
     * @return string
     * @throws Exception
     */
    public function actionHook()
    {
        switch(Yii::$app->getRequest()->getUserAgent()) {
            case 'Bitbucket-Webhooks/2.0':
                $type = Repository::REPOSITORY_BITBUCKET;
                break;
            case 'GitHub-Hookshot/cd33156':
                $type = Repository::REPOSITORY_GITHUB;
                break;
            default:
                throw new ForbiddenHttpException('Вам не разрешено производить данное действие');
        }

        $json = Yii::$app->getRequest()->getRawBody();

        //file_put_contents(__DIR__ . '/__get_github.json', $json);
        //$json = file_get_contents(__DIR__ . '/__get_github.json');

        if (!empty($json)) {
            $host = Yii::$app->params['WebSocketServer-host'] ?: 'localhost';
            $port = Yii::$app->params['WebSocketServer-port'] ?: 8000;

            if($type == Repository::REPOSITORY_BITBUCKET) {
                $info = Helper::trimByKey(json_decode($json, true), 'uuid', '{}');
            } else {
                $info = json_decode($json, true);
            }

            $info['type'] = $type;

            $client = new Client("ws://" . $host . ":" . $port . "/");
            $client->send(json_encode([
                'hookFileCache' => [
                    'alias' => $info['repository']['full_name'],
                    'fileName' => Helper::cacheData(json_encode($info)),
                ],
            ]));
            echo $client->receive();
        }
    }

}

app/frontend/views/project/_tabs/_access_management.php
<?php
use yii\widgets\Pjax;
use common\models\Project;
use common\models\User;
use frontend\widgets\User\AccessGridView;
use goodizer\helpers\ModelHelper;

/**
 * @var $this yii\web\View
 * @var $model Project
 */
$this->registerJsFile($this->getAssetManager()->publish(Yii::getAlias('@webroot/js/project/access-management.js'))[1], [
    'depends' => [\frontend\assets\AppAsset::className()]
]);

$user = new User(['scenario' => 'access-management']);
$query = $model->getUsers()->where(['status' => User::STATUS_ACTIVE]);

if ($user->load(Yii::$app->getRequest()->get()) && !empty($user->email)) {
    $query = User::find()->where(['LIKE', 'email', $user->email]);
}

$form = \yii\bootstrap\ActiveForm::begin([
    'id' => 'user-management-form',
    'method' => 'get',
    'action' => \yii\helpers\Url::to(['/project/view', 'id' => $model->id]),
]);
echo $form->field($user, 'email')->label(Yii::t('user', 'Search by email:'));
$form->end();

Pjax::begin(['id' => 'user-management-list']);
echo AccessGridView::widget(ModelHelper::search(new User(['scenario' => 'access-management']), ['query' => $query]) + [
        'attrItemBody' => function (User $u) use($model){
            if($u->getHasProject()->andWhere(['project_id' => $model->id])->one()) {
                return ' class="grid-checked-row"';
            }

            return null;
        }
    ]);
Pjax::end();

app/frontend/views/project/_tabs/_chat_list.php
<?php
use common\models\Project;

/**
 * @var $this yii\web\View
 * @var $model Project
 */

$this->registerJsFile($this->getAssetManager()->publish(Yii::getAlias('@webroot/js/project/modal.js'))[1], [
    'depends' => [\frontend\assets\AppAsset::className()]
]);
?>
<?= Yii::$app->getUser()->can('project/create-chat')
    ? \yii\helpers\Html::button(Yii::t('system', 'Create chat'), [
        'class' => 'btn btn-success',
        'data-toggle' => 'modal',
        'data-target' => '#create-chat-modal',
        'data-action-url' => \yii\helpers\Url::to(['create-chat', 'id' => $model->id]),
    ])
    : '' ?>
    <hr/>

<?php \yii\widgets\Pjax::begin(['id' => 'chat-update']) ?>
<?= \frontend\widgets\Chat\GridView::widget(
    \common\helpers\ModelHelper::search(new \common\models\Chat(['project_id' => $model->id]))
) ?>
<?php \yii\widgets\Pjax::end() ?>

<?php
if (Yii::$app->getUser()->can('project/create-chat')) {
    \yii\bootstrap\Modal::begin([
        'header' => '<h3>New chat for "' . $model->name . '"</h3>',
        'id' => 'create-chat-modal',
    ]);
    \yii\bootstrap\Modal::end();
}

\yii\bootstrap\Modal::begin([
    'header' => '<h3>New chat for "' . $model->name . '"</h3>',
    'id' => 'chat-manage-access',
]);
\yii\bootstrap\Modal::end();
?>

app/frontend/views/project/_tabs/_detail.php
<?php
use common\models\Project;
use frontend\widgets\Project\DetailView;

/**
 * @var $this yii\web\View
 * @var $model Project
 */

echo \yii\bootstrap\ButtonGroup::widget([
    'buttons' => [
        [
            'label' => Yii::t('system', 'Back'),
            'tagName' => 'a',
            'options' => [
                'href' => \yii\helpers\Url::to('index'),
                'class' => 'btn btn-danger'
            ],
        ],
        [
            'label' => Yii::t('system', 'Edit'),
            'tagName' => 'a',
            'options' => [
                'href' => \yii\helpers\Url::to(['update', 'id' => $model->id]),
                'class' => 'btn btn-success'
            ],
            'visible' => Yii::$app->getUser()->can('project/update', ['model' => $model, 'attribute' => 'owner_id']),
        ],
    ]
]);
?>
    <hr/>
<?= DetailView::widget([
    'model' => $model
]) ?>

app/frontend/views/project/_tabs/_repository_list.php
<?php
use common\models\Project;
use yii\helpers\Html;

/**
 * @var $this yii\web\View
 * @var $model Project
 */
?>
<?= Yii::$app->getUser()->can('repository/create')
    ? (Html::a(Yii::t('system', 'New repository'), ['/repository/create', 'pid' => $model->id], [
            'class' => 'btn btn-success'
        ]) . '<hr/>') : '' ?>
<?= \frontend\widgets\Repository\GridView::widget(
    \common\helpers\ModelHelper::search(new \common\models\Repository(['project_id' => $model->id]))
) ?>