app/common/models/Chat.php
<?php
namespace common\models;

use common\models\ext\AR;
use Yii;
use yii\base\Exception;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\Expression;
use yii\db\Schema;

/**
 * Chat model
 *
 * @property integer $id
 * @property integer $project_id
 * @property integer $owner_id
 * @property string $name
 * @property string $description
 * @property integer $status
 * @property boolean $enable_repository_events
 * @property string $updated_at
 * @property string $created_at
 *
 * @property integer $connectedUserId
 * @property array $connectedUserIds
 */
class Chat extends AR
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%tbl_chat}}';
    }

    /**
     * @inheritdoc
     */
    public function attributeTypes()
    {
        return [
            'id' => Schema::TYPE_PK,
            'project_id' => Schema::TYPE_INTEGER,
            'owner_id' => Schema::TYPE_INTEGER,
            'name' => Schema::TYPE_STRING,
            'description' => Schema::TYPE_TEXT,
            'enable_repository_events' => Schema::TYPE_BOOLEAN,
            'status' => Schema::TYPE_SMALLINT,
            'updated_at' => Schema::TYPE_TIMESTAMP,
            'created_at' => Schema::TYPE_TIMESTAMP,
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => '#',
            'project_id' => 'Project',
            'owner_id' => 'Пользователь',
            'name' => 'Имя',
            'description' => 'Контент',
            'enable_repository_events' => 'Notify repository events',
            'status' => 'Статус',
            'updated_at' => 'Обновлено',
            'created_at' => 'Добавлено',
        ];
    }

    /**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			[
				'class' => TimestampBehavior::className(),
				'value' => new Expression('NOW()')
			]
		];
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['name', 'description', 'enable_repository_events', 'status', 'created_at'], 'safe'],
			[['name'], 'required', 'on' => 'create-chat'],
		];
	}

    /**
     * @return ActiveQuery
     */
    public function getHasNotices()
    {
        return $this->hasMany(ChatHasNotice::className(), ['chat_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getNotices()
    {
        return $this->hasMany(Notice::className(), ['id' => 'notice_id'])->via('hasNotices');
    }

    /**
     * @return ActiveQuery
     */
    public function getRepository()
    {
        return $this->hasOne(Repository::className(), ['project_id' => 'project_id']);
    }

    /**
     * @return User
     */
    public function getOwner()
    {
        return $this->hasOne(User::className(), ['id' => 'owner_id'])->one();
    }

    /**
     * @return ActiveQuery
     */
    public function getHasUser()
    {
        return $this->hasMany(ChatHasUser::className(), ['chat_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getUserByAccess()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])->via('hasUser');
    }
}

app/frontend/controllers/ChatController.php
<?php
namespace frontend\controllers;

use common\models\Chat;
use common\models\ChatHasUser;
use common\models\Project;
use common\models\User;
use frontend\filters\AccessRule;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\Response;

/**
 * Class ChatController
 */
class ChatController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'class' => AccessRule::className(),
                    ],
                ],
            ],
        ];
    }

    /**
     * @param $id
     * @return string enable_repository_events
     */
    public function actionIndex($id)
    {
        $this->layout = 'chat.php';

        return $this->render('index', ['id' => $id]);
    }

    /**
     * @param $id
     * @param $toAll
     * @param $userId
     * @return string
     */
    public function actionGrandAccess($id, $toAll, $userId = null)
    {
        VarDumper::dump(Yii::$app->user->id);

        return '';
    }

    /**
     * @param $id
     * @return string
     * @throws BadRequestHttpException
     */
    public function actionManageAccess($id)
    {
        if (!Yii::$app->getRequest()->isAjax) {
            throw new BadRequestHttpException("Not found!", 404);
        }

        /** @var Chat $chat */
        if (!($chat = Chat::findOne($id))) {
            throw new BadRequestHttpException("Not found!", 404);
        }

        $old = $chat->getUserByAccess()->asArray()->all();
        $oldIds = array_values(ArrayHelper::map($old, 'id', 'id'));
        $new = User::find()
            ->where(['not in', 'id', $oldIds])
            ->andWhere(['status' => User::STATUS_ACTIVE])
            ->asArray()->all();

        $list = ArrayHelper::merge($new, $old);

        foreach ($list as $k => $val) {
            $list[$k]['checked'] = in_array($val['id'], $oldIds);
        }

        usort($list, function ($a, $b) {
            return (int)$a['id'] > (int)$b['id'];
        });

        return $this->renderPartial('_checkbox', [
            'id' => $chat->id,
            'list' => $list
        ]);
    }

}

app/frontend/views/chat/_checkbox.php
<?php
/**
 * @var $this yii\web\View
 * @var $id integer
 * @var $list array
 */
?>
<?= \frontend\widgets\User\MinGridView::widget([
    'dataProvider' => new \yii\data\ArrayDataProvider([
        'allModels' => $list
    ]),
    'options' => [
        'class' => 'grid-view',
        'data-action-url' => \yii\helpers\Url::to(['/chat/grand-access', 'id' => $id]),
    ]
]) ?>

app/frontend/views/chat/edit.php
<?php
/**
 * @var $this yii\web\View
 * @var $model \common\models\Chat
 */

?>
<div class="row">
    <div class="col-lg-12">
        <div class="blocked-bg"></div>
        <?php
        $form = \frontend\widgets\ActiveForm::begin();
        echo \frontend\widgets\Chat\SaveForm::fields($form, $model);
        ?>
        <hr/>
        <?php
        echo \yii\helpers\Html::submitButton('Save', ['class' => 'btn btn-success']);
        $form->end();
        ?>
    </div>
</div>

app/frontend/views/chat/index.php
<?php
use \yii\helpers\Html;

/**
 * @var $this yii\web\View
 * @var $id integer|null
 */
\ext\WebSocket\Asset::register($this);

$this->title = 'Tracker chat';
?>
    <div id="chat" class="chat">
        <div class="row">
            <div class="col-xs-9">
                <div class="notice-content">
                    <div class="notice-show-more">
                        <a href="javascript://" class="btn btn-success notice-show-more-button">Show more</a>
                    </div>
                    <div class="notice-list">
                        <div class="notice-item--loader">
                            <div>
                                <div class="three-quarters-loader">Loading...</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-3">
                <h4>User list</h4>

                <div class="user-content">
                    <div class="user-list">

                    </div>
                </div>
                <br/>
                <a href="/repository/hook">test</a>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-9">
                <form id="notice-form">
                    <?= Html::label(
                        'Scroll to bottom?' . Html::checkbox('scrollToBottom', true, ['id' => 'scroll-to-bottom']),
                        'scroll-to-bottom'
                    ) ?>
                    <div class="btn-group-xs">
                        <?= Html::button('Button', ['class' => 'btn btn-success']) ?>
                        <?= Html::button('Button', ['class' => 'btn btn-success']) ?>
                        <?= Html::button('Button', ['class' => 'btn btn-success']) ?>
                        <?= Html::button('Button', ['class' => 'btn btn-success']) ?>
                        <?= Html::button('Button', ['class' => 'btn btn-success']) ?>
                        <?= Html::button('Button', ['class' => 'btn btn-success']) ?>
                    </div>
                    <div class="clearfix"></div>
                    <hr>
                    <?= Html::textarea('Notice[message]', '', ['class' => 'form-control']) ?>
                    <hr>
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </form>
            </div>
            <div class="col-xs-3">
            </div>
        </div>
    </div>

    <script id="notice-item" type="text/html">
        <div class="notice-item__row">
            <div class="notice-item__id"></div>
            <div class="notice-item__type"></div>
            <div class="notice-item__owner"></div>
        </div>
        <div class="notice-item__text"></div>
        <div class="notice-item__created"></div>
    </script>

    <script id="user-item" type="text/html">
        <div class="user-item__status"><span></span></div>
        <div class="user-item__username"></div>
        <div class="user-item__role"></div>
    </script>

<?php
$this->registerJs(
    'window.app = new Application('
    . \yii\helpers\Json::encode([
        'chatId' => $id,
        'registerId' => Yii::$app->user->id,
        'sessionId' => Yii::$app->session->getId(),
        'socketOptions' => [
            'host' => 'localhost',
            'port' => 8000,
        ]
    ])
    . ');'
);