app/common/models/Project.php
<?php
namespace common\models;

use common\models\ext\AR;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\Expression;
use yii\db\Schema;

/**
 * Project model
 *
 * @property integer $id
 * @property integer $owner_id
 * @property string $name
 * @property string $description
 * @property integer $status
 * @property string $updated_at
 * @property string $created_at
 */
class Project extends AR
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%tbl_project}}';
    }

    /**
     * @inheritdoc
     */
    public function attributeTypes()
    {
        return [
            'id' => Schema::TYPE_PK,
            'owner_id' => Schema::TYPE_INTEGER,
            'name' => Schema::TYPE_STRING,
            'description' => Schema::TYPE_TEXT,
            'status' => Schema::TYPE_SMALLINT,
            'updated_at' => Schema::TYPE_TIMESTAMP,
            'created_at' => Schema::TYPE_TIMESTAMP,
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => '#',
            'owner_id' => Yii::t('project', 'User'),
            'name' => Yii::t('project', 'Name'),
            'description' => Yii::t('project', 'Description'),
            'status' => Yii::t('project', 'Status'),
            'updated_at' => Yii::t('project', 'Updated at'),
            'created_at' => Yii::t('project', 'Created at'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'value' => new Expression('NOW()')
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description', 'status', 'updated_at', 'created_at'], 'safe'],
        ];
    }

    /**
     * @return User
     */
    public function getOwner()
    {
        return $this->hasOne('\common\models\User', ['id' => 'owner_id'])->one();
    }

    /**
     * @return Chat[]
     */
    public function getChats()
    {
        return $this->hasOne('\common\models\Chat', ['project_id' => 'id'])->all();
    }

    /**
     * @return ActiveQuery
     */
    public function getHasUser()
    {
        return $this->hasMany(ProjectHasUser::className(), ['project_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])->via('hasUser');
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert = true)
    {
        $this->status = Project::STATUS_ACTIVE;
        $this->owner_id = Yii::$app->getUser()->getId();

        return parent::beforeSave($insert);
    }
}

app/frontend/controllers/ProjectController.php
<?php
namespace frontend\controllers;

use common\models\Chat;
use common\models\ChatHasUser;
use common\models\Project;
use common\models\Repository;
use common\models\User;
use frontend\filters\AccessRule;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * Class ProjectController
 */
class ProjectController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'class' => AccessRule::className(),
                    ],
                ],
            ],
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'logout' => ['post'],
//                ],
//            ],
        ];
	}

	/**
	 * @return string
	 */
	public function actionIndex()
	{
        return $this->render('index');
	}

    /**
     * @param null $id
     * @return string|Response
     */
	public function actionCreate($id = null)
	{
        if(!$id || null === ($project = Project::findOne($id))) {
            $project = new Project();
        }

        if($project->load(Yii::$app->request->post())) {
            $project->status = Project::STATUS_ACTIVE;
            $project->owner_id = Yii::$app->getUser()->getId();

            if($project->save()) {
                return $this->redirect(Url::to('index'));
            }
        }

		return $this->render('edit', ['project' => $project]);
	}

    /**
     * @param $id
     * @return string|Response
     */
	public function actionUpdate($id)
	{
		return $this->actionCreate($id);
	}

	/**
	 * @param $id
	 * @return string
	 */
	public function actionView($id)
	{
        $project = Project::findById($id);

        return $this->render('view', ['model' => $project]);
	}

    /**
     * @param $id
     * @return string
     * @throws BadRequestHttpException
     */
    public function actionCreateChat($id)
    {
        if(!Yii::$app->getRequest()->isAjax) {
            throw new BadRequestHttpException("Not found!", 404);
        }

        $project = Project::findById($id);

        $chat = new Chat([
            'project_id' => $project->id,
            'owner_id' => Yii::$app->user->getId(),
            'name' => $project->name . ' - Chat',
        ]);

        $chat->setScenario('create-chat');

        if($chat->load(Yii::$app->request->get())) {
            Yii::$app->response->format = Response::FORMAT_JSON;

            $chat->status = User::STATUS_ACTIVE;
            $errors = ActiveForm::validate($chat, $chat->attributes());

            if(empty($errors) && $chat->save()) {
                $chatUser = new ChatHasUser();
                $chatUser->chat_id = $chat->id;
                $chatUser->user_id = $chat->owner_id;
                $chatUser->save();
            }

            return $errors;
        }

        return $this->renderPartial('/chat/edit', ['model' => $chat]);
    }


}

app/frontend/views/project/edit.php
<?php
/**
 * @var $this yii\web\View
 * @var $project \common\models\Project
 */

$this->title = Yii::t('project', 'Start your own project');
?>
<div class="Project-index">
    <h1><?= $this->title ?></h1>
    <hr/>
    <?php $form = \frontend\widgets\ActiveForm::begin() ?>

    <?= \frontend\widgets\Project\SaveForm::fields($form, $project) ?>
    <hr/>
    <?= \yii\helpers\Html::submitButton('Save', ['class' => 'btn btn-success']) ?>

    <?php $form->end() ?>
</div>

app/frontend/views/project/index.php
<?php
/**
 * @var $this yii\web\View
 */
\ext\WebSocket\Asset::register($this);

$this->title = 'Projects';
?>
<div class="Project-index">

    <h1>Projects</h1>

    <hr/>

    <?= \yii\helpers\Html::a('New project', '/project/create', ['class' => 'btn btn-primary']) ?>

    <hr/>

    <?= \frontend\widgets\Project\GridView::widget(
        \common\helpers\ModelHelper::search(new \common\models\Project())
    ) ?>

</div>

app/frontend/views/project/view.php
<?php
use common\models\Project;
use kartik\tabs\TabsX;

/**
 * @var $this yii\web\View
 * @var $model Project
 */
$this->title = 'Project';

echo TabsX::widget([
    'containerOptions' => [
        'class' => 'tabs-with-large'
    ],
    'position' => TabsX::POS_LEFT,
    'bordered' => true,
    'items' => [
        [
            'label' => Yii::t('headers', 'Project detail'),
            'content' => $this->render('_tabs/_detail', ['model' => $model]),
        ],
        [
            'label' => Yii::t('headers', 'Repository list'),
            'content' => $this->render('_tabs/_repository_list', ['model' => $model]),
        ],
        [
            'label' => Yii::t('headers', 'Chat list'),
            'content' => $this->render('_tabs/_chat_list', ['model' => $model]),
        ],
        [
            'label' => Yii::t('headers', 'Access management'),
            'content' => $this->render('_tabs/_access_management', ['model' => $model]),
            'visible' => Yii::$app->getUser()->can('project/update', ['model' => $model, 'attribute' => 'owner_id']),
            'active' => true
        ]
    ],
]);