app/frontend/controllers/RepositoryController.php
<?php
namespace frontend\controllers;

use common\models\Repository;
use ext\Repository\Helper;
use ext\WebSocket\Client;
use frontend\filters\AccessRule;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;

/**
 * Class RepositoryController
 */
class RepositoryController extends Controller
{
    /**
     * @var bool
     */
    public $enableCsrfValidation = false;

    /**
     * @inheritdoc
     */
//    public function behaviors()
//    {
//        return [
//            'access' => [
//                'class' => AccessControl::className(),
//                'rules' => [
//                    [
//                        'class' => AccessRule::className(),
//                    ],
//                ],
//            ],
//        ];
//    }

    /**
     * @param integer
     * @return string
     */
    public function actionCreate($pid)
    {
        $project = new Repository();

        if (is_numeric($pid) && $project->load(Yii::$app->request->post())) {
            $project->status = Repository::STATUS_ACTIVE;
            $project->owner_id = Yii::$app->getUser()->getId();
            $project->project_id = $pid;

            if ($project->save()) {
                return $this->redirect(Url::to(['/project/view', 'id' => $pid]));
            }
        }

        return $this->render('edit', ['project' => $project]);
    }

    /**
     * @return string
     * @throws Exception
     */
    public function actionHook()
    {
        switch(Yii::$app->getRequest()->getUserAgent()) {
            case 'Bitbucket-Webhooks/2.0':
                $type = Repository::REPOSITORY_BITBUCKET;
                break;
            case 'GitHub-Hookshot/cd33156':
                $type = Repository::REPOSITORY_GITHUB;
                break;
            default:
                throw new ForbiddenHttpException('Вам не разрешено производить данное действие');
        }

        $json = Yii::$app->getRequest()->getRawBody();

        //file_put_contents(__DIR__ . '/__get_github.json', $json);
        //$json = file_get_contents(__DIR__ . '/__get_github.json');

        if (!empty($json)) {
            $host = Yii::$app->params['WebSocketServer-host'] ?: 'localhost';
            $port = Yii::$app->params['WebSocketServer-port'] ?: 8000;

            if($type == Repository::REPOSITORY_BITBUCKET) {
                $info = Helper::trimByKey(json_decode($json, true), 'uuid', '{}');
            } else {
                $info = json_decode($json, true);
            }

            $info['type'] = $type;

            $client = new Client("ws://" . $host . ":" . $port . "/");
            $client->send(json_encode([
                'hookFileCache' => [
                    'alias' => $info['repository']['full_name'],
                    'fileName' => Helper::cacheData(json_encode($info)),
                ],
            ]));
            echo $client->receive();
        }
    }

}

app/frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Project;
use common\models\User;
use Yii;
use common\forms\Login;
use yii\base\InvalidParamException;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => false,
                        //'allow' => true,
                        //'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'logout' => ['post'],
//                ],
//            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionLogin()
    {
        if(!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new Login();
        if($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @return string
     */
    public function actionSignUp()
    {
        $model = new User(['scenario' => 'sign-up']);

        if ($model->load(Yii::$app->request->post(), 'User')) {
            $authManager = Yii::$app->getAuthManager();
            $transaction = $model->getDb()->beginTransaction();
            $password = $model->password_hash;
            $model->setPassword($model->password_hash);
            $model->generateAuthKey();
            $model->status = User::STATUS_ACTIVE;
            $model->role = $model->role ?: User::ROLE_DEVELOPER;

            if ($model->save()) {
                $transaction->commit();
                $login = new Login();
                $login->username = $model->username;
                $login->password = $password;
                $login->rememberMe = true;

                $authManager->assign($authManager->getRole($model->role), $model->id);

                if($login->login()) {
                    return $this->redirect(Url::to('/'));
                } else {
                    return $this->redirect(Url::to('/site/login'));
                }
            } else {
                $transaction->rollBack();
                $model->password_hash = $password;
            }
        }

        return $this->render('sign-up', ['model' => $model]);
    }


}

app/frontend/views/layouts/chat.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use frontend\widgets\Alert;
use \yii\helpers\Url;

/**
 * @var $this \yii\web\View
 * @var $content string
 * @var $user \common\models\User
 */

AppAsset::register($this);

$ctrlName = Yii::$app->controller->id;
$actionName = Yii::$app->controller->action->id;

$user = Yii::$app->user->identity;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="chat-content-wrapper">
    <?= $content ?>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

app/frontend/views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use frontend\widgets\Alert;
use \yii\helpers\Url;

/**
 * @var $this \yii\web\View
 * @var $content string
 * @var $user \common\models\User
 */

AppAsset::register($this);

$ctrlName = Yii::$app->controller->id;
$actionName = Yii::$app->controller->action->id;

$user = Yii::$app->user->identity;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div id="wrapper" class="content-wrapper">
    <?php
    NavBar::begin(['brandLabel' => 'New project']);
    echo Nav::widget([
        'items' => [
            ['label' => 'Projects', 'url' => ['/project']],
            ['label' => 'Hook Test', 'url' => ['/repository/hook']],
        ],
        'options' => ['class' => 'navbar-nav'],
    ]);
    echo Nav::widget([
        'items' => Yii::$app->user->isGuest
            ? [
                ['label' => 'Registration', 'url' => ['/site/sign-up']],
                ['label' => 'Login', 'url' => ['/site/login']],
            ]
            : [
                [
                    'label' => 'RBAC',
                    'url' => '/rbac',
                    'visible' => $user->role == \common\models\User::ROLE_ADMIN,
                ],
                ['label' => 'Logout(' . $user->email . ')', 'url' => ['/site/logout']],
            ],
        'options' => ['class' => 'navbar-nav pull-right'],
    ]);
    NavBar::end();
    ?>
    <div class="container">
        <?= Alert::widget() ?>
        <?=
        Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>
<div class="footer-wrapper">
    <div class="footer">
        <p class="pull-left">&copy; Союз <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>